name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: simple_bank_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root -d simple_bank_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/
          migrate -version

      - name: Run database migrations
        env:
          DB_SOURCE: "postgresql://postgres:postgres@localhost:5432/simple_bank_test?sslmode=disable"
        run: |
          make migrateup
      - name: Run Go tests
        env:
          DB_SOURCE: "postgresql://root:secret@localhost:5432/simple_bank_test?sslmode=disable"
        run: go test -v ./...

      - name: Run Go linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          golangci-lint run ./...
